# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "trackdechets"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "trackdechets"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  trackdechets:
    # Config indicated by + and applies to all files under models/example/
    +dbt-osmosis: "_{model}.yml"

    refined_zone:
      analytics:
        +materialized: view
        +schema: refined_zone_analytics
      icpe:
        +schema: refined_zone_icpe
        gerep:
          +materialized: ephemeral
      enriched:
        +schema: refined_zone_enriched
      stats_publiques:
        +schema: refined_zone_stats_publiques
      gistrid:
        +schema: refined_zone_gistrid
      observatoires:
        +schema: refined_zone_observatoires

    trusted_zone:
      +schema: trusted_zone
      gsheet:
        +schema: trusted_zone_gsheet
      insee:
        +schema: trusted_zone_insee
      trackdechets:
        +schema: trusted_zone_trackdechets
      icpe:
        +schema: trusted_zone_icpe
      zammad:
        +schema: trusted_zone_zammad
      gerep:
        +schema: trusted_zone_gerep
      gistrid:
        +schema: trusted_zone_gistrid
      rndts:
        +schema: trusted_zone_rndts
      gerico:
        +schema: trusted_zone_gerico
      referentials:
        +schema: trusted_zone_referentials





seeds:
  trackdechets:
    +schema: raw_zone_referentials
    +dbt-osmosis: "_schema.yml"

