services:
  clickhouse:
    image: clickhouse:24.12
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8123:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
      - ./config.d:/etc/clickhouse-server/config.d
      - ./users.d:/etc/clickhouse-server/users.d
      - ./logs:/var/log/clickhouse-server
    restart: unless-stopped
