-- data_eng."AnonymousCompany" source

CREATE OR REPLACE VIEW data_eng."AnonymousCompany"
AS SELECT "AnonymousCompany".id,
    "AnonymousCompany".siret,
    "AnonymousCompany".name,
    "AnonymousCompany".address,
    "AnonymousCompany"."codeNaf",
    "AnonymousCompany"."libelleNaf",
    "AnonymousCompany"."codeCommune",
    "AnonymousCompany"."vatNumber",
    "AnonymousCompany"."orgId",
    "AnonymousCompany"."etatAdministratif"
   FROM "default$default"."AnonymousCompany";

-- data_eng."BrokerReceipt" source

CREATE OR REPLACE VIEW data_eng."BrokerReceipt"
AS SELECT "BrokerReceipt".id,
    "BrokerReceipt"."receiptNumber",
    "BrokerReceipt"."validityLimit",
    "BrokerReceipt".department
   FROM "default$default"."BrokerReceipt";

-- data_eng."Bsda" source

CREATE OR REPLACE VIEW data_eng."Bsda"
AS SELECT "Bsda".id,
    "Bsda"."createdAt",
    "Bsda"."updatedAt",
    "Bsda"."isDraft",
    "Bsda"."isDeleted",
    "Bsda".status,
    "Bsda".type,
    "Bsda"."emitterIsPrivateIndividual",
    "Bsda"."emitterCompanyName",
    "Bsda"."emitterCompanySiret",
    "Bsda"."emitterCompanyAddress",
    "Bsda"."emitterCompanyContact",
    "Bsda"."emitterCompanyPhone",
    "Bsda"."emitterCompanyMail",
    "Bsda"."emitterPickupSiteName",
    "Bsda"."emitterPickupSiteAddress",
    "Bsda"."emitterPickupSiteCity",
    "Bsda"."emitterPickupSitePostalCode",
    "Bsda"."emitterPickupSiteInfos",
    "Bsda"."emitterEmissionSignatureAuthor",
    "Bsda"."emitterEmissionSignatureDate",
    "Bsda"."wasteCode",
    "Bsda"."wasteFamilyCode",
    "Bsda"."wasteMaterialName",
    "Bsda"."wasteConsistence",
    "Bsda"."wasteSealNumbers"::text AS "wasteSealNumbers",
    "Bsda"."wasteAdr",
    "Bsda".packagings,
    "Bsda"."weightValue",
    "Bsda"."destinationCompanyName",
    "Bsda"."destinationCompanySiret",
    "Bsda"."destinationCompanyAddress",
    "Bsda"."destinationCompanyContact",
    "Bsda"."destinationCompanyPhone",
    "Bsda"."destinationCompanyMail",
    "Bsda"."destinationCap",
    "Bsda"."destinationPlannedOperationCode",
    "Bsda"."destinationReceptionDate",
    "Bsda"."destinationReceptionWeight",
    "Bsda"."destinationReceptionAcceptationStatus",
    "Bsda"."destinationReceptionRefusalReason",
    "Bsda"."destinationReceptionRefusedWeight",
    "Bsda"."destinationOperationCode",
    "Bsda"."destinationOperationDate",
    "Bsda"."destinationOperationSignatureAuthor",
    "Bsda"."destinationOperationSignatureDate",
    "Bsda"."transporterTransportSignatureDate",
    "Bsda"."workerCompanyName",
    "Bsda"."workerCompanySiret",
    "Bsda"."workerCompanyAddress",
    "Bsda"."workerCompanyContact",
    "Bsda"."workerCompanyPhone",
    "Bsda"."workerCompanyMail",
    "Bsda"."workerWorkHasEmitterPaperSignature",
    "Bsda"."workerWorkSignatureAuthor",
    "Bsda"."workerWorkSignatureDate",
    "Bsda"."brokerCompanyName",
    "Bsda"."brokerCompanySiret",
    "Bsda"."brokerCompanyAddress",
    "Bsda"."brokerCompanyContact",
    "Bsda"."brokerCompanyPhone",
    "Bsda"."brokerCompanyMail",
    "Bsda"."brokerRecepisseNumber",
    "Bsda"."brokerRecepisseDepartment",
    "Bsda"."brokerRecepisseValidityLimit",
    "Bsda"."destinationOperationNextDestinationCompanyName",
    "Bsda"."destinationOperationNextDestinationCompanySiret",
    "Bsda"."destinationOperationNextDestinationCompanyVatNumber",
    "Bsda"."destinationOperationNextDestinationCompanyAddress",
    "Bsda"."destinationOperationNextDestinationCompanyContact",
    "Bsda"."destinationOperationNextDestinationCompanyPhone",
    "Bsda"."destinationOperationNextDestinationCompanyMail",
    "Bsda"."destinationOperationNextDestinationCap",
    "Bsda"."destinationOperationNextDestinationPlannedOperationCode",
    "Bsda"."weightIsEstimate",
    "Bsda"."emitterCustomInfo",
    "Bsda"."destinationCustomInfo",
    "Bsda"."ecoOrganismeName",
    "Bsda"."ecoOrganismeSiret",
    "Bsda"."forwardingId",
    "Bsda"."groupedInId",
    "Bsda"."wastePop",
    "Bsda"."destinationOperationDescription",
    "Bsda"."workerIsDisabled",
    "Bsda"."workerCertificationHasSubSectionFour",
    "Bsda"."workerCertificationHasSubSectionThree",
    "Bsda"."workerCertificationCertificationNumber",
    "Bsda"."workerCertificationValidityLimit",
    "Bsda"."workerCertificationOrganisation",
    "Bsda"."intermediariesOrgIds"::text AS "intermediariesOrgIds",
    "Bsda"."destinationOperationMode",
    "Bsda"."transportersOrgIds"::text AS "transportersOrgIds",
    "Bsda"."rowNumber",
    "Bsda"."canAccessDraftOrgIds"::text AS "canAccessDraftOrgIds"
   FROM "default$default"."Bsda";

-- data_eng."BsdaRevisionRequest" source

CREATE OR REPLACE VIEW data_eng."BsdaRevisionRequest"
AS SELECT "BsdaRevisionRequest".id,
    "BsdaRevisionRequest"."createdAt",
    "BsdaRevisionRequest"."updatedAt",
    "BsdaRevisionRequest"."bsdaId",
    "BsdaRevisionRequest"."authoringCompanyId",
    "BsdaRevisionRequest".comment,
    "BsdaRevisionRequest".status,
    "BsdaRevisionRequest"."wasteCode",
    "BsdaRevisionRequest"."wastePop",
    "BsdaRevisionRequest".packagings,
    "BsdaRevisionRequest"."wasteSealNumbers"::text AS "wasteSealNumbers",
    "BsdaRevisionRequest"."wasteMaterialName",
    "BsdaRevisionRequest"."destinationCap",
    "BsdaRevisionRequest"."destinationReceptionWeight",
    "BsdaRevisionRequest"."destinationOperationCode",
    "BsdaRevisionRequest"."destinationOperationDescription",
    "BsdaRevisionRequest"."brokerCompanyName",
    "BsdaRevisionRequest"."brokerCompanySiret",
    "BsdaRevisionRequest"."brokerCompanyAddress",
    "BsdaRevisionRequest"."brokerCompanyContact",
    "BsdaRevisionRequest"."brokerCompanyPhone",
    "BsdaRevisionRequest"."brokerCompanyMail",
    "BsdaRevisionRequest"."brokerRecepisseNumber",
    "BsdaRevisionRequest"."brokerRecepisseDepartment",
    "BsdaRevisionRequest"."brokerRecepisseValidityLimit",
    "BsdaRevisionRequest"."emitterPickupSiteName",
    "BsdaRevisionRequest"."emitterPickupSiteAddress",
    "BsdaRevisionRequest"."emitterPickupSiteCity",
    "BsdaRevisionRequest"."emitterPickupSitePostalCode",
    "BsdaRevisionRequest"."emitterPickupSiteInfos",
    "BsdaRevisionRequest"."isCanceled",
    "BsdaRevisionRequest"."destinationOperationMode",
    "BsdaRevisionRequest"."initialBrokerCompanyAddress",
    "BsdaRevisionRequest"."initialBrokerCompanyContact",
    "BsdaRevisionRequest"."initialBrokerCompanyMail",
    "BsdaRevisionRequest"."initialBrokerCompanyName",
    "BsdaRevisionRequest"."initialBrokerCompanyPhone",
    "BsdaRevisionRequest"."initialBrokerCompanySiret",
    "BsdaRevisionRequest"."initialBrokerRecepisseDepartment",
    "BsdaRevisionRequest"."initialBrokerRecepisseNumber",
    "BsdaRevisionRequest"."initialBrokerRecepisseValidityLimit",
    "BsdaRevisionRequest"."initialDestinationCap",
    "BsdaRevisionRequest"."initialDestinationOperationCode",
    "BsdaRevisionRequest"."initialDestinationOperationDescription",
    "BsdaRevisionRequest"."initialDestinationOperationMode",
    "BsdaRevisionRequest"."initialDestinationReceptionWeight",
    "BsdaRevisionRequest"."initialEmitterPickupSiteAddress",
    "BsdaRevisionRequest"."initialEmitterPickupSiteCity",
    "BsdaRevisionRequest"."initialEmitterPickupSiteInfos",
    "BsdaRevisionRequest"."initialEmitterPickupSiteName",
    "BsdaRevisionRequest"."initialEmitterPickupSitePostalCode",
    "BsdaRevisionRequest"."initialPackagings",
    "BsdaRevisionRequest"."initialWasteCode",
    "BsdaRevisionRequest"."initialWasteMaterialName",
    "BsdaRevisionRequest"."initialWastePop",
    "BsdaRevisionRequest"."initialWasteSealNumbers"::text AS "initialWasteSealNumbers"
   FROM "default$default"."BsdaRevisionRequest";

-- data_eng."BsdaTransporter" source

CREATE OR REPLACE VIEW data_eng."BsdaTransporter"
AS SELECT "BsdaTransporter".id,
    "BsdaTransporter"."createdAt",
    "BsdaTransporter"."updatedAt",
    "BsdaTransporter".number,
    "BsdaTransporter"."bsdaId",
    "BsdaTransporter"."transporterCompanySiret",
    "BsdaTransporter"."transporterCompanyName",
    "BsdaTransporter"."transporterCompanyVatNumber",
    "BsdaTransporter"."transporterCompanyAddress",
    "BsdaTransporter"."transporterCompanyContact",
    "BsdaTransporter"."transporterCompanyPhone",
    "BsdaTransporter"."transporterCompanyMail",
    "BsdaTransporter"."transporterCustomInfo",
    "BsdaTransporter"."transporterRecepisseIsExempted",
    "BsdaTransporter"."transporterRecepisseNumber",
    "BsdaTransporter"."transporterRecepisseDepartment",
    "BsdaTransporter"."transporterRecepisseValidityLimit",
    "BsdaTransporter"."transporterTransportMode",
    "BsdaTransporter"."transporterTransportPlates"::text AS "transporterTransportPlates",
    "BsdaTransporter"."transporterTransportTakenOverAt",
    "BsdaTransporter"."transporterTransportSignatureAuthor",
    "BsdaTransporter"."transporterTransportSignatureDate"
   FROM "default$default"."BsdaTransporter";

-- data_eng."Bsdasri" source

CREATE OR REPLACE VIEW data_eng."Bsdasri"
AS SELECT "Bsdasri".id,
    "Bsdasri".status,
    "Bsdasri"."createdAt",
    "Bsdasri"."updatedAt",
    "Bsdasri"."isDeleted",
    "Bsdasri"."isDraft",
    "Bsdasri"."emitterCompanyName",
    "Bsdasri"."emitterCompanySiret",
    "Bsdasri"."emitterCompanyAddress",
    "Bsdasri"."emitterCompanyContact",
    "Bsdasri"."emitterCompanyPhone",
    "Bsdasri"."emitterCompanyMail",
    "Bsdasri"."emitterPickupSiteName",
    "Bsdasri"."emitterPickupSiteAddress",
    "Bsdasri"."emitterPickupSiteCity",
    "Bsdasri"."emitterPickupSitePostalCode",
    "Bsdasri"."emitterPickupSiteInfos",
    "Bsdasri"."wasteCode",
    "Bsdasri"."wasteAdr",
    "Bsdasri"."emitterWasteWeightValue",
        CASE
            WHEN "Bsdasri"."emitterWasteVolume" < 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001::double precision THEN 0::double precision
            WHEN "Bsdasri"."emitterWasteVolume" > '1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'::numeric::double precision THEN 'Infinity'::double precision
            ELSE "Bsdasri"."emitterWasteVolume"
        END AS "emitterWasteVolume",
    "Bsdasri"."emitterWastePackagings",
    "Bsdasri"."emitterCustomInfo",
    "Bsdasri"."emitterEmissionSignatureAuthor",
    "Bsdasri"."emitterEmissionSignatureDate",
    "Bsdasri"."isEmissionDirectTakenOver",
    "Bsdasri"."isEmissionTakenOverWithSecretCode",
    "Bsdasri"."transporterCompanyName",
    "Bsdasri"."transporterCompanySiret",
    "Bsdasri"."transporterCompanyAddress",
    "Bsdasri"."transporterCompanyPhone",
    "Bsdasri"."transporterCompanyContact",
    "Bsdasri"."transporterCompanyMail",
    "Bsdasri"."transporterRecepisseNumber",
    "Bsdasri"."transporterRecepisseDepartment",
    "Bsdasri"."transporterRecepisseValidityLimit",
    "Bsdasri"."transporterAcceptationStatus",
    "Bsdasri"."transporterWasteRefusalReason",
    "Bsdasri"."transporterWasteRefusedWeightValue",
    "Bsdasri"."transporterTakenOverAt",
    "Bsdasri"."transporterWastePackagings",
    "Bsdasri"."transporterWasteWeightValue",
        CASE
            WHEN "Bsdasri"."transporterWasteVolume" < 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001::double precision THEN 0::double precision
            WHEN "Bsdasri"."transporterWasteVolume" > '1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'::numeric::double precision THEN 'Infinity'::double precision
            ELSE "Bsdasri"."transporterWasteVolume"
        END AS "transporterWasteVolume",
    "Bsdasri"."transporterCustomInfo",
    "Bsdasri"."handedOverToRecipientAt",
    "Bsdasri"."transporterTransportSignatureAuthor",
    "Bsdasri"."transporterTransportSignatureDate",
    "Bsdasri"."destinationCompanyName",
    "Bsdasri"."destinationCompanySiret",
    "Bsdasri"."destinationCompanyAddress",
    "Bsdasri"."destinationCompanyContact",
    "Bsdasri"."destinationCompanyPhone",
    "Bsdasri"."destinationCompanyMail",
    "Bsdasri"."destinationWastePackagings",
    "Bsdasri"."destinationReceptionAcceptationStatus",
    "Bsdasri"."destinationReceptionWasteRefusalReason",
    "Bsdasri"."destinationReceptionWasteRefusedWeightValue",
    "Bsdasri"."destinationReceptionWasteWeightValue",
        CASE
            WHEN "Bsdasri"."destinationReceptionWasteVolume" < 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001::double precision THEN 0::double precision
            WHEN "Bsdasri"."destinationReceptionWasteVolume" > '1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'::numeric::double precision THEN 'Infinity'::double precision
            ELSE "Bsdasri"."destinationReceptionWasteVolume"
        END AS "destinationReceptionWasteVolume",
    "Bsdasri"."destinationCustomInfo",
    "Bsdasri"."destinationReceptionDate",
    "Bsdasri"."destinationOperationCode",
    "Bsdasri"."destinationOperationDate",
    "Bsdasri"."destinationReceptionSignatureAuthor",
    "Bsdasri"."destinationReceptionSignatureDate",
    "Bsdasri"."destinationOperationSignatureDate",
    "Bsdasri"."destinationOperationSignatureAuthor",
    "Bsdasri"."emissionSignatoryId",
    "Bsdasri"."transportSignatoryId",
    "Bsdasri"."receptionSignatoryId",
    "Bsdasri"."operationSignatoryId",
    "Bsdasri"."groupedInId",
    "Bsdasri"."transporterTransportMode",
    "Bsdasri".type,
    "Bsdasri"."emitterWasteWeightIsEstimate",
    "Bsdasri"."transporterWasteWeightIsEstimate",
    "Bsdasri"."ecoOrganismeName",
    "Bsdasri"."ecoOrganismeSiret",
    "Bsdasri"."transporterTransportPlates"::text AS "transporterTransportPlates",
    "Bsdasri"."identificationNumbers"::text AS "identificationNumbers",
    "Bsdasri"."transporterCompanyVatNumber",
    "Bsdasri"."synthesizedInId",
    "Bsdasri"."emittedByEcoOrganisme",
    "Bsdasri"."synthesisEmitterSirets"::text AS "synthesisEmitterSirets",
    "Bsdasri"."transporterRecepisseIsExempted",
    "Bsdasri"."groupingEmitterSirets"::text AS "groupingEmitterSirets",
    "Bsdasri"."destinationOperationMode",
    "Bsdasri"."rowNumber",
    "Bsdasri"."intermediariesOrgIds"::text AS "intermediariesOrgIds",
    "Bsdasri"."brokerCompanyName",
    "Bsdasri"."brokerCompanySiret",
    "Bsdasri"."brokerCompanyAddress",
    "Bsdasri"."brokerCompanyContact",
    "Bsdasri"."brokerCompanyPhone",
    "Bsdasri"."brokerCompanyMail",
    "Bsdasri"."brokerRecepisseNumber",
    "Bsdasri"."brokerRecepisseDepartment",
    "Bsdasri"."brokerRecepisseValidityLimit",
    "Bsdasri"."traderCompanyName",
    "Bsdasri"."traderCompanySiret",
    "Bsdasri"."traderCompanyAddress",
    "Bsdasri"."traderCompanyContact",
    "Bsdasri"."traderCompanyPhone",
    "Bsdasri"."traderCompanyMail",
    "Bsdasri"."traderRecepisseNumber",
    "Bsdasri"."traderRecepisseDepartment",
    "Bsdasri"."traderRecepisseValidityLimit"
   FROM "default$default"."Bsdasri";

-- data_eng."BsdasriRevisionRequest" source

CREATE OR REPLACE VIEW data_eng."BsdasriRevisionRequest"
AS SELECT "BsdasriRevisionRequest".id,
    "BsdasriRevisionRequest"."createdAt",
    "BsdasriRevisionRequest"."updatedAt",
    "BsdasriRevisionRequest".status,
    "BsdasriRevisionRequest".comment,
    "BsdasriRevisionRequest"."isCanceled",
    "BsdasriRevisionRequest"."bsdasriId",
    "BsdasriRevisionRequest"."authoringCompanyId",
    "BsdasriRevisionRequest"."wasteCode",
    "BsdasriRevisionRequest"."destinationWastePackagings",
    "BsdasriRevisionRequest"."destinationReceptionWasteWeightValue",
    "BsdasriRevisionRequest"."destinationOperationCode",
    "BsdasriRevisionRequest"."destinationOperationMode",
    "BsdasriRevisionRequest"."emitterPickupSiteName",
    "BsdasriRevisionRequest"."emitterPickupSiteAddress",
    "BsdasriRevisionRequest"."emitterPickupSiteCity",
    "BsdasriRevisionRequest"."emitterPickupSitePostalCode",
    "BsdasriRevisionRequest"."emitterPickupSiteInfos",
    "BsdasriRevisionRequest"."initialDestinationOperationCode",
    "BsdasriRevisionRequest"."initialDestinationOperationMode",
    "BsdasriRevisionRequest"."initialDestinationReceptionWasteWeightValue",
    "BsdasriRevisionRequest"."initialDestinationWastePackagings",
    "BsdasriRevisionRequest"."initialEmitterPickupSiteAddress",
    "BsdasriRevisionRequest"."initialEmitterPickupSiteCity",
    "BsdasriRevisionRequest"."initialEmitterPickupSiteInfos",
    "BsdasriRevisionRequest"."initialEmitterPickupSiteName",
    "BsdasriRevisionRequest"."initialEmitterPickupSitePostalCode",
    "BsdasriRevisionRequest"."initialWasteCode"
   FROM "default$default"."BsdasriRevisionRequest";

-- data_eng."BsddRevisionRequest" source

CREATE OR REPLACE VIEW data_eng."BsddRevisionRequest"
AS SELECT "BsddRevisionRequest".id,
    "BsddRevisionRequest"."createdAt",
    "BsddRevisionRequest"."updatedAt",
    "BsddRevisionRequest"."bsddId",
    "BsddRevisionRequest"."authoringCompanyId",
    "BsddRevisionRequest".comment,
    "BsddRevisionRequest".status,
    "BsddRevisionRequest"."recipientCap",
    "BsddRevisionRequest"."wasteDetailsCode",
    "BsddRevisionRequest"."wasteDetailsPop",
    "BsddRevisionRequest"."quantityReceived",
    "BsddRevisionRequest"."processingOperationDone",
    "BsddRevisionRequest"."brokerCompanyName",
    "BsddRevisionRequest"."brokerCompanySiret",
    "BsddRevisionRequest"."brokerCompanyAddress",
    "BsddRevisionRequest"."brokerCompanyContact",
    "BsddRevisionRequest"."brokerCompanyPhone",
    "BsddRevisionRequest"."brokerCompanyMail",
    "BsddRevisionRequest"."brokerReceipt",
    "BsddRevisionRequest"."brokerDepartment",
    "BsddRevisionRequest"."brokerValidityLimit",
    "BsddRevisionRequest"."traderCompanyAddress",
    "BsddRevisionRequest"."traderCompanyContact",
    "BsddRevisionRequest"."traderCompanyPhone",
    "BsddRevisionRequest"."traderCompanyMail",
    "BsddRevisionRequest"."traderReceipt",
    "BsddRevisionRequest"."traderDepartment",
    "BsddRevisionRequest"."traderValidityLimit",
    "BsddRevisionRequest"."temporaryStorageDestinationCap",
    "BsddRevisionRequest"."temporaryStorageDestinationProcessingOperation",
    "BsddRevisionRequest"."traderCompanySiret",
    "BsddRevisionRequest"."traderCompanyName",
    "BsddRevisionRequest"."wasteDetailsName",
    "BsddRevisionRequest"."wasteDetailsPackagingInfos",
    "BsddRevisionRequest"."processingOperationDescription",
    "BsddRevisionRequest"."temporaryStorageTemporaryStorerQuantityReceived",
    "BsddRevisionRequest"."isCanceled",
    "BsddRevisionRequest"."destinationOperationMode",
    "BsddRevisionRequest"."wasteDetailsQuantity",
    "BsddRevisionRequest"."wasteDetailsSampleNumber",
    "BsddRevisionRequest"."quantityRefused",
    "BsddRevisionRequest"."wasteAcceptationStatus",
    "BsddRevisionRequest"."wasteRefusalReason",
    "BsddRevisionRequest"."initialBrokerCompanyAddress",
    "BsddRevisionRequest"."initialBrokerCompanyContact",
    "BsddRevisionRequest"."initialBrokerCompanyMail",
    "BsddRevisionRequest"."initialBrokerCompanyName",
    "BsddRevisionRequest"."initialBrokerCompanyPhone",
    "BsddRevisionRequest"."initialBrokerCompanySiret",
    "BsddRevisionRequest"."initialBrokerDepartment",
    "BsddRevisionRequest"."initialBrokerReceipt",
    "BsddRevisionRequest"."initialBrokerValidityLimit",
    "BsddRevisionRequest"."initialDestinationOperationMode",
    "BsddRevisionRequest"."initialProcessingOperationDescription",
    "BsddRevisionRequest"."initialProcessingOperationDone",
    "BsddRevisionRequest"."initialQuantityReceived",
    "BsddRevisionRequest"."initialQuantityRefused",
    "BsddRevisionRequest"."initialRecipientCap",
    "BsddRevisionRequest"."initialTemporaryStorageDestinationCap",
    "BsddRevisionRequest"."initialTemporaryStorageDestinationProcessingOperation",
    "BsddRevisionRequest"."initialTemporaryStorageTemporaryStorerQuantityReceived",
    "BsddRevisionRequest"."initialTraderCompanyAddress",
    "BsddRevisionRequest"."initialTraderCompanyContact",
    "BsddRevisionRequest"."initialTraderCompanyMail",
    "BsddRevisionRequest"."initialTraderCompanyName",
    "BsddRevisionRequest"."initialTraderCompanyPhone",
    "BsddRevisionRequest"."initialTraderCompanySiret",
    "BsddRevisionRequest"."initialTraderDepartment",
    "BsddRevisionRequest"."initialTraderReceipt",
    "BsddRevisionRequest"."initialTraderValidityLimit",
    "BsddRevisionRequest"."initialWasteAcceptationStatus",
    "BsddRevisionRequest"."initialWasteDetailsCode",
    "BsddRevisionRequest"."initialWasteDetailsName",
    "BsddRevisionRequest"."initialWasteDetailsPackagingInfos",
    "BsddRevisionRequest"."initialWasteDetailsPop",
    "BsddRevisionRequest"."initialWasteDetailsQuantity",
    "BsddRevisionRequest"."initialWasteDetailsSampleNumber",
    "BsddRevisionRequest"."initialWasteRefusalReason"
   FROM "default$default"."BsddRevisionRequest";

-- data_eng."BsddTransporter" source

CREATE OR REPLACE VIEW data_eng."BsddTransporter"
AS SELECT "BsddTransporter".id,
    "BsddTransporter".number,
    "BsddTransporter"."transporterCompanySiret",
    "BsddTransporter"."transporterCompanyName",
    "BsddTransporter"."transporterCompanyAddress",
    "BsddTransporter"."transporterCompanyContact",
    "BsddTransporter"."transporterCompanyPhone",
    "BsddTransporter"."transporterCompanyMail",
    "BsddTransporter"."transporterIsExemptedOfReceipt",
    "BsddTransporter"."transporterReceipt",
    "BsddTransporter"."transporterDepartment",
    "BsddTransporter"."transporterValidityLimit",
    "BsddTransporter"."transporterNumberPlate",
    "BsddTransporter"."transporterTransportMode",
    "BsddTransporter"."readyToTakeOver",
    "BsddTransporter"."takenOverAt",
    "BsddTransporter"."takenOverBy",
    "BsddTransporter"."createdAt",
    "BsddTransporter"."updatedAt",
    "BsddTransporter"."formId",
    "BsddTransporter"."previousTransporterCompanyOrgId",
    "BsddTransporter"."transporterCompanyVatNumber",
    "BsddTransporter"."transporterCustomInfo"
   FROM "default$default"."BsddTransporter";

-- data_eng."Bsff" source

CREATE OR REPLACE VIEW data_eng."Bsff"
AS SELECT "Bsff".id,
    "Bsff"."createdAt",
    "Bsff"."updatedAt",
    "Bsff"."isDeleted",
    "Bsff"."emitterCompanyName",
    "Bsff"."emitterCompanySiret",
    "Bsff"."emitterCompanyAddress",
    "Bsff"."emitterCompanyContact",
    "Bsff"."emitterCompanyPhone",
    "Bsff"."emitterCompanyMail",
    "Bsff"."emitterEmissionSignatureAuthor",
    "Bsff"."emitterEmissionSignatureDate",
    "Bsff"."wasteCode",
    "Bsff"."wasteAdr",
    "Bsff"."weightValue",
    "Bsff"."weightIsEstimate",
    "Bsff"."transporterTransportSignatureDate",
    "Bsff"."destinationCompanyName",
    "Bsff"."destinationCompanySiret",
    "Bsff"."destinationCompanyAddress",
    "Bsff"."destinationCompanyContact",
    "Bsff"."destinationCompanyPhone",
    "Bsff"."destinationCompanyMail",
    "Bsff"."destinationReceptionDate",
    "Bsff"."destinationReceptionSignatureAuthor",
    "Bsff"."destinationReceptionSignatureDate",
    "Bsff"."destinationPlannedOperationCode",
    "Bsff".status,
    "Bsff"."wasteDescription",
    "Bsff"."isDraft",
    "Bsff".type,
    "Bsff"."destinationCustomInfo",
    "Bsff"."emitterCustomInfo",
    "Bsff"."destinationCap",
    "Bsff"."detenteurCompanySirets"::text AS "detenteurCompanySirets",
    "Bsff"."rowNumber",
    "Bsff"."transportersOrgIds"::text AS "transportersOrgIds"
   FROM "default$default"."Bsff";

-- data_eng."BsffPackaging" source

CREATE OR REPLACE VIEW data_eng."BsffPackaging"
AS SELECT "BsffPackaging".id,
    "BsffPackaging".volume,
    "BsffPackaging".weight,
    "BsffPackaging".numero,
    "BsffPackaging"."bsffId",
    "BsffPackaging"."acceptationDate",
    "BsffPackaging"."acceptationRefusalReason",
    "BsffPackaging"."acceptationSignatureAuthor",
    "BsffPackaging"."acceptationSignatureDate",
    "BsffPackaging"."acceptationStatus",
    "BsffPackaging"."acceptationWeight",
    "BsffPackaging"."acceptationWasteCode",
    "BsffPackaging"."acceptationWasteDescription",
    "BsffPackaging"."operationDate",
    "BsffPackaging"."operationCode",
    "BsffPackaging"."operationDescription",
    "BsffPackaging"."operationNoTraceability",
    "BsffPackaging"."operationSignatureAuthor",
    "BsffPackaging"."operationSignatureDate",
    "BsffPackaging"."operationNextDestinationPlannedOperationCode",
    "BsffPackaging"."operationNextDestinationCap",
    "BsffPackaging"."operationNextDestinationCompanyAddress",
    "BsffPackaging"."operationNextDestinationCompanyContact",
    "BsffPackaging"."operationNextDestinationCompanyMail",
    "BsffPackaging"."operationNextDestinationCompanyName",
    "BsffPackaging"."operationNextDestinationCompanyPhone",
    "BsffPackaging"."operationNextDestinationCompanySiret",
    "BsffPackaging"."operationNextDestinationCompanyVatNumber",
    "BsffPackaging"."nextPackagingId",
    "BsffPackaging".other,
    "BsffPackaging".type,
    "BsffPackaging"."emissionNumero",
    "BsffPackaging"."operationMode"
   FROM "default$default"."BsffPackaging";

-- data_eng."BsffTransporter" source

CREATE OR REPLACE VIEW data_eng."BsffTransporter"
AS SELECT "BsffTransporter".id,
    "BsffTransporter"."createdAt",
    "BsffTransporter"."updatedAt",
    "BsffTransporter".number,
    "BsffTransporter"."bsffId",
    "BsffTransporter"."transporterCompanySiret",
    "BsffTransporter"."transporterCompanyName",
    "BsffTransporter"."transporterCompanyVatNumber",
    "BsffTransporter"."transporterCompanyAddress",
    "BsffTransporter"."transporterCompanyContact",
    "BsffTransporter"."transporterCompanyPhone",
    "BsffTransporter"."transporterCompanyMail",
    "BsffTransporter"."transporterCustomInfo",
    "BsffTransporter"."transporterRecepisseIsExempted",
    "BsffTransporter"."transporterRecepisseNumber",
    "BsffTransporter"."transporterRecepisseDepartment",
    "BsffTransporter"."transporterRecepisseValidityLimit",
    "BsffTransporter"."transporterTransportMode",
    "BsffTransporter"."transporterTransportPlates"::text AS "transporterTransportPlates",
    "BsffTransporter"."transporterTransportTakenOverAt",
    "BsffTransporter"."transporterTransportSignatureAuthor",
    "BsffTransporter"."transporterTransportSignatureDate"
   FROM "default$default"."BsffTransporter";

-- data_eng."Bsvhu" source

CREATE OR REPLACE VIEW data_eng."Bsvhu"
AS SELECT "Bsvhu".id,
    "Bsvhu"."createdAt",
    "Bsvhu"."updatedAt",
    "Bsvhu"."isDraft",
    "Bsvhu"."isDeleted",
    "Bsvhu".status,
    "Bsvhu"."emitterAgrementNumber",
    "Bsvhu"."emitterCompanyName",
    "Bsvhu"."emitterCompanySiret",
    "Bsvhu"."emitterCompanyAddress",
    "Bsvhu"."emitterCompanyContact",
    "Bsvhu"."emitterCompanyPhone",
    "Bsvhu"."emitterCompanyMail",
    "Bsvhu"."destinationType",
    "Bsvhu"."destinationPlannedOperationCode",
    "Bsvhu"."destinationAgrementNumber",
    "Bsvhu"."destinationCompanyName",
    "Bsvhu"."destinationCompanySiret",
    "Bsvhu"."destinationCompanyAddress",
    "Bsvhu"."destinationCompanyContact",
    "Bsvhu"."destinationCompanyPhone",
    "Bsvhu"."destinationCompanyMail",
    "Bsvhu"."wasteCode",
    "Bsvhu".packaging,
    "Bsvhu"."identificationNumbers"::text AS "identificationNumbers",
    "Bsvhu"."identificationType",
    "Bsvhu".quantity,
    "Bsvhu"."weightValue",
    "Bsvhu"."emitterEmissionSignatureAuthor",
    "Bsvhu"."emitterEmissionSignatureDate",
     "Bsvhu"."destinationReceptionAcceptationStatus",
    "Bsvhu"."destinationReceptionRefusalReason",
    "Bsvhu"."destinationReceptionIdentificationNumbers"::text AS "destinationReceptionIdentificationNumbers",
    "Bsvhu"."destinationReceptionIdentificationType",
    "Bsvhu"."destinationOperationCode",
    "Bsvhu"."destinationOperationNextDestinationCompanyName",
    "Bsvhu"."destinationOperationNextDestinationCompanySiret",
    "Bsvhu"."destinationOperationNextDestinationCompanyAddress",
    "Bsvhu"."destinationOperationNextDestinationCompanyContact",
    "Bsvhu"."destinationOperationNextDestinationCompanyPhone",
    "Bsvhu"."destinationOperationNextDestinationCompanyMail",
    "Bsvhu"."destinationOperationSignatureAuthor",
    "Bsvhu"."destinationOperationSignatureDate",
     "Bsvhu"."destinationOperationDate",
    "Bsvhu"."destinationReceptionQuantity",
    "Bsvhu"."destinationReceptionWeight",
    "Bsvhu"."destinationReceptionDate",
    "Bsvhu"."weightIsEstimate",
    "Bsvhu"."destinationOperationNextDestinationCompanyVatNumber",
    "Bsvhu"."emitterCustomInfo","Bsvhu"."destinationCustomInfo",
    "Bsvhu"."destinationOperationMode",
    "Bsvhu"."rowNumber",
    "Bsvhu"."emitterIrregularSituation",
    "Bsvhu"."emitterNoSiret",
    "Bsvhu"."emitterCompanyCity",
    "Bsvhu"."emitterCompanyCountry",
    "Bsvhu"."emitterCompanyPostalCode",
    "Bsvhu"."emitterCompanyStreet",
    "Bsvhu"."intermediariesOrgIds"::text AS "intermediariesOrgIds",
    "Bsvhu"."ecoOrganismeName",
    "Bsvhu"."ecoOrganismeSiret",
    "Bsvhu"."brokerCompanyAddress",
    "Bsvhu"."brokerCompanyContact",
    "Bsvhu"."brokerCompanyMail",
    "Bsvhu"."brokerCompanyName",
    "Bsvhu"."brokerCompanyPhone",
    "Bsvhu"."brokerCompanySiret",
    "Bsvhu"."brokerRecepisseDepartment",
    "Bsvhu"."brokerRecepisseNumber",
    "Bsvhu"."brokerRecepisseValidityLimit",
    "Bsvhu"."traderCompanyAddress",
    "Bsvhu"."traderCompanyContact",
    "Bsvhu"."traderCompanyMail",
    "Bsvhu"."traderCompanyName",
    "Bsvhu"."traderCompanyPhone",
    "Bsvhu"."traderCompanySiret",
    "Bsvhu"."traderRecepisseDepartment",
    "Bsvhu"."traderRecepisseNumber",
    "Bsvhu"."traderRecepisseValidityLimit",
    "Bsvhu"."canAccessDraftOrgIds"::text AS "canAccessDraftOrgIds",
    "Bsvhu"."transportersOrgIds"::text AS "transportersOrgIds",
    "Bsvhu"."customId"
   FROM "default$default"."Bsvhu";


CREATE OR REPLACE VIEW data_eng."BsvhuTransporter"
AS SELECT "BsvhuTransporter".id,
    "BsvhuTransporter"."createdAt",
    "BsvhuTransporter"."updatedAt",
    "BsvhuTransporter".number,
    "BsvhuTransporter"."bsvhuId",
    "BsvhuTransporter"."transporterCompanySiret",
    "BsvhuTransporter"."transporterCompanyName",
    "BsvhuTransporter"."transporterCompanyVatNumber",
    "BsvhuTransporter"."transporterCompanyAddress",
    "BsvhuTransporter"."transporterCompanyContact",
    "BsvhuTransporter"."transporterCompanyPhone",
    "BsvhuTransporter"."transporterCompanyMail",
    "BsvhuTransporter"."transporterCustomInfo",
    "BsvhuTransporter"."transporterRecepisseIsExempted",
    "BsvhuTransporter"."transporterRecepisseNumber",
    "BsvhuTransporter"."transporterRecepisseDepartment",
    "BsvhuTransporter"."transporterRecepisseValidityLimit",
    "BsvhuTransporter"."transporterTransportMode",
    "BsvhuTransporter"."transporterTransportPlates"::text AS "transporterTransportPlates",
    "BsvhuTransporter"."transporterTransportTakenOverAt",
    "BsvhuTransporter"."transporterTransportSignatureAuthor",
    "BsvhuTransporter"."transporterTransportSignatureDate"
   FROM "default$default"."BsvhuTransporter";

-- data_eng."Company" source

CREATE OR REPLACE VIEW data_eng."Company"
AS SELECT "Company".id,
    "Company".siret,
    "Company"."updatedAt",
    "Company"."createdAt",
    "Company"."securityCode",
    "Company".name,
    "Company"."gerepId",
    "Company"."codeNaf",
    "Company"."givenName",
    "Company"."contactEmail",
    "Company"."contactPhone",
    "Company".website,
    "Company"."transporterReceiptId",
    "Company"."traderReceiptId",
    "Company"."ecoOrganismeAgreements"::text AS "ecoOrganismeAgreements",
    "Company"."companyTypes"::text AS "companyTypes",
    "Company".address,
    "Company".latitude,
    "Company".longitude,
    "Company"."brokerReceiptId",
    "Company"."verificationCode",
    "Company"."verificationStatus",
    "Company"."verificationMode",
    "Company"."verificationComment",
    "Company"."verifiedAt",
    "Company"."vhuAgrementDemolisseurId",
    "Company"."vhuAgrementBroyeurId",
    "Company"."allowBsdasriTakeOverWithoutSignature",
    "Company"."vatNumber",
    "Company".contact,
    "Company"."codeDepartement",
    "Company"."workerCertificationId",
    "Company"."orgId",
    "Company"."collectorTypes"::text AS "collectorTypes",
    "Company"."wasteProcessorTypes"::text AS "wasteProcessorTypes",
    "Company"."webhookSettingsLimit",
    "Company"."allowAppendix1SignatureAutomation",
    "Company"."featureFlags"::text AS "featureFlags",
    "Company"."wasteVehiclesTypes"::text AS "wasteVehiclesTypes",
    "Company"."isDormantSince",
    "Company"."hasEnabledRegistryDndFromBsdSince",
    "Company"."ecoOrganismePartnersIds"
   FROM "default$default"."Company";

-- data_eng."CompanyAssociation" source

CREATE OR REPLACE VIEW data_eng."CompanyAssociation"
AS SELECT "CompanyAssociation".id,
    "CompanyAssociation".role,
    "CompanyAssociation"."companyId",
    "CompanyAssociation"."userId",
    "CompanyAssociation"."createdAt",
    "CompanyAssociation"."automaticallyAccepted",
    "CompanyAssociation"."notificationIsActiveBsdRefusal",
    "CompanyAssociation"."notificationIsActiveBsdaFinalDestinationUpdate",
    "CompanyAssociation"."notificationIsActiveMembershipRequest",
    "CompanyAssociation"."notificationIsActiveRevisionRequest",
    "CompanyAssociation"."notificationIsActiveSignatureCodeRenewal"
   FROM "default$default"."CompanyAssociation";

-- data_eng."EcoOrganisme" source

CREATE OR REPLACE VIEW data_eng."EcoOrganisme"
AS SELECT "EcoOrganisme".id,
    "EcoOrganisme".siret,
    "EcoOrganisme".name,
    "EcoOrganisme".address,
    "EcoOrganisme"."handleBsdasri",
    "EcoOrganisme"."handleBsda",
    "EcoOrganisme"."handleBsvhu"
   FROM "default$default"."EcoOrganisme";

-- data_eng."Form" source

CREATE OR REPLACE VIEW data_eng."Form"
AS SELECT "Form".id,
    "Form"."createdAt",
    "Form"."updatedAt",
    "Form"."emitterType",
    "Form"."emitterPickupSite",
    "Form"."emitterCompanyName",
    "Form"."emitterCompanySiret",
    "Form"."emitterCompanyAddress",
    "Form"."emitterCompanyContact",
    "Form"."emitterCompanyPhone",
    "Form"."emitterCompanyMail",
    "Form"."recipientCap",
    "Form"."recipientProcessingOperation",
    "Form"."recipientCompanyName",
    "Form"."recipientCompanySiret",
    "Form"."recipientCompanyAddress",
    "Form"."recipientCompanyContact",
    "Form"."recipientCompanyPhone",
    "Form"."recipientCompanyMail",
    "Form"."wasteDetailsCode",
    "Form"."wasteDetailsOnuCode",
    "Form"."wasteDetailsQuantity",
    "Form"."wasteDetailsQuantityType",
    "Form"."readableId",
    "Form".status,
    "Form"."sentAt",
    "Form"."sentBy",
    "Form"."isAccepted",
    "Form"."receivedAt",
    "Form"."quantityReceived",
    "Form"."processingOperationDone",
    "Form"."wasteDetailsName",
    "Form"."isDeleted",
    "Form"."receivedBy",
    "Form"."wasteDetailsConsistence"::text AS "wasteDetailsConsistence",
    "Form"."processedBy",
    "Form"."processedAt",
    "Form"."nextDestinationProcessingOperation",
    "Form"."traderCompanyName",
    "Form"."traderCompanySiret",
    "Form"."traderCompanyAddress",
    "Form"."traderCompanyContact",
    "Form"."traderCompanyPhone",
    "Form"."traderCompanyMail",
    "Form"."traderReceipt",
    "Form"."traderDepartment",
    "Form"."traderValidityLimit",
    "Form"."processingOperationDescription",
    "Form"."noTraceability",
    "Form"."signedByTransporter",
    "Form"."customId",
    "Form"."wasteAcceptationStatus",
    "Form"."wasteRefusalReason",
    "Form"."nextDestinationCompanyName",
    "Form"."nextDestinationCompanySiret",
    "Form"."nextDestinationCompanyAddress",
    "Form"."nextDestinationCompanyContact",
    "Form"."nextDestinationCompanyPhone",
    "Form"."nextDestinationCompanyMail",
    "Form"."emitterWorkSiteName",
    "Form"."emitterWorkSiteAddress",
    "Form"."emitterWorkSiteCity",
    "Form"."emitterWorkSitePostalCode",
    "Form"."emitterWorkSiteInfos",
    "Form"."recipientIsTempStorage",
    "Form"."signedAt",
    "Form"."currentTransporterOrgId",
    "Form"."nextTransporterOrgId",
    "Form"."nextDestinationCompanyCountry",
    "Form"."isImportedFromPaper",
    "Form"."ecoOrganismeName",
    "Form"."ecoOrganismeSiret",
    "Form"."wasteDetailsPackagingInfos",
    "Form"."signedBy",
    "Form"."wasteDetailsPop",
    "Form"."ownerId",
    "Form"."brokerCompanyName",
    "Form"."brokerCompanySiret",
    "Form"."brokerCompanyAddress",
    "Form"."brokerCompanyContact",
    "Form"."brokerCompanyPhone",
    "Form"."brokerCompanyMail",
    "Form"."brokerReceipt",
    "Form"."brokerDepartment",
    "Form"."brokerValidityLimit",
    "Form"."wasteDetailsIsDangerous",
    "Form"."emittedAt",
    "Form"."emittedBy",
    "Form"."emittedByEcoOrganisme",
    "Form"."takenOverAt",
    "Form"."takenOverBy",
    "Form"."wasteDetailsParcelNumbers",
    "Form"."wasteDetailsAnalysisReferences"::text AS "wasteDetailsAnalysisReferences",
    "Form"."wasteDetailsLandIdentifiers"::text AS "wasteDetailsLandIdentifiers",
    "Form"."forwardedInId",
    "Form"."quantityReceivedType",
    "Form"."emitterIsForeignShip",
    "Form"."emitterIsPrivateIndividual",
    "Form"."emitterCompanyOmiNumber",
    "Form"."nextDestinationCompanyVatNumber",
    "Form"."recipientsSirets"::text AS "recipientsSirets",
    "Form"."transportersSirets"::text AS "transportersSirets",
    "Form"."intermediariesSirets"::text AS "intermediariesSirets",
    "Form"."nextDestinationNotificationNumber",
    "Form"."wasteDetailsSampleNumber",
    "Form"."canAccessDraftSirets"::text AS "canAccessDraftSirets",
    "Form"."destinationOperationMode",
    "Form"."quantityGrouped",
    "Form"."nextDestinationCompanyExtraEuropeanId",
    "Form"."rowNumber",
    "Form"."quantityRefused",
    "Form"."citerneNotWashedOutReason",
    "Form"."hasCiterneBeenWashedOut",
    "Form"."emptyReturnADR",
    "Form"."wasteDetailsNonRoadRegulationMention",
    "Form"."wasteDetailsIsSubjectToADR"
   FROM "default$default"."Form";

-- data_eng."TraderReceipt" source

CREATE OR REPLACE VIEW data_eng."TraderReceipt"
AS SELECT "TraderReceipt".id,
    "TraderReceipt"."receiptNumber",
    "TraderReceipt"."validityLimit",
    "TraderReceipt".department
   FROM "default$default"."TraderReceipt";

-- data_eng."TransporterReceipt" source

CREATE OR REPLACE VIEW data_eng."TransporterReceipt"
AS SELECT "TransporterReceipt".id,
    "TransporterReceipt"."receiptNumber",
    "TransporterReceipt"."validityLimit",
    "TransporterReceipt".department
   FROM "default$default"."TransporterReceipt";

-- data_eng."User" source

CREATE OR REPLACE VIEW data_eng."User"
AS SELECT "User".id,
    "User".email,
    "User".password,
    "User".name,
    "User".phone,
    "User"."createdAt",
    "User"."updatedAt",
    "User"."isActive",
    "User"."activatedAt",
    "User"."firstAssociationDate",
    "User"."isAdmin",
    "User"."passwordUpdatedAt",
    "User"."governmentAccountId"
   FROM "default$default"."User";

-- data_eng."VhuAgrement" source

CREATE OR REPLACE VIEW data_eng."VhuAgrement"
AS SELECT "VhuAgrement".id,
    "VhuAgrement"."agrementNumber",
    "VhuAgrement".department
   FROM "default$default"."VhuAgrement";



-- data_eng."WorkerCertification" source

CREATE OR REPLACE VIEW data_eng."WorkerCertification"
AS SELECT
	id,
	"hasSubSectionFour",
	"hasSubSectionThree",
	"certificationNumber",
	"validityLimit",
	organisation
FROM "default$default"."WorkerCertification";

-- data_eng."Bspaoh" source

CREATE OR REPLACE VIEW data_eng."Bspaoh"
AS SELECT
	id,
	"createdAt",
	"updatedAt",
	"isDeleted",
	"status",
	"wasteCode",
	"wasteAdr",
	"wasteType",
	"wastePackagings",
	"emitterCompanyName",
	"emitterCompanySiret",
	"emitterCompanyAddress",
	"emitterCompanyContact",
	"emitterCompanyPhone",
	"emitterCompanyMail",
	"emitterCustomInfo",
	"emitterPickupSiteName",
	"emitterPickupSiteAddress",
	"emitterPickupSiteCity",
	"emitterPickupSitePostalCode",
	"emitterPickupSiteInfos",
	"emitterWasteQuantityValue",
	"emitterWasteWeightValue",
	"emitterWasteWeightIsEstimate",
	"emitterEmissionSignatureAuthor",
	"emitterEmissionSignatureDate",
	"transporterTransportTakenOverAt",
	"destinationCompanyName",
	"destinationCompanySiret",
	"destinationCompanyAddress",
	"destinationCompanyContact",
	"destinationCompanyPhone",
	"destinationCompanyMail",
	"destinationCustomInfo",
	"destinationCap",
	"handedOverToDestinationSignatureDate",
	"handedOverToDestinationSignatureAuthor",
	"destinationReceptionWasteQuantityValue",
	"destinationReceptionAcceptationStatus",
	"destinationReceptionWasteRefusalReason",
	"destinationReceptionWastePackagingsAcceptation",
	"destinationReceptionDate",
	"destinationReceptionSignatureDate",
	"destinationReceptionSignatureAuthor",
	"destinationOperationCode",
	"destinationOperationDate",
	"destinationOperationSignatureDate",
	"destinationOperationSignatureAuthor",
	"currentTransporterOrgId",
	"nextTransporterOrgId",
	"transportersSirets",
	"canAccessDraftSirets",
	"rowNumber",
	"destinationReceptionWasteAcceptedWeightValue",
	"destinationReceptionWasteReceivedWeightValue",
	"destinationReceptionWasteRefusedWeightValue",
	"isDuplicateOf"
FROM
	"default$default"."Bspaoh";

-- data_eng."BspaohTransporter" source

create or replace
view data_eng."BspaohTransporter"
as
select
	id,
	"createdAt",
	"updatedAt",
	"number",
	"transporterCompanyName",
	"transporterCompanySiret",
	"transporterCompanyVatNumber",
	"transporterCompanyAddress",
	"transporterCompanyContact",
	"transporterCompanyPhone",
	"transporterCompanyMail",
	"transporterTransportMode",
	"transporterCustomInfo",
	"bspaohId",
	"transporterRecepisseDepartment",
	"transporterRecepisseIsExempted",
	"transporterRecepisseNumber",
	"transporterRecepisseValidityLimit",
	"transporterTakenOverAt",
	"transporterTransportPlates",
	"transporterTransportSignatureAuthor",
	"transporterTransportSignatureDate"
from
	"default$default"."BspaohTransporter";

-- data_eng."RegistryIncomingTexs" source
CREATE OR REPLACE VIEW data_eng."RegistryIncomingTexs"
AS
SELECT
	id,
	"createdAt",
    "updatedAt",
	"importId",
	"isLatest",
	"isCancelled",
	"createdById",
	"publicId",
	"reportForCompanySiret",
	"reportForCompanyName",
	"reportForCompanyAddress",
	"reportForCompanyCity",
	"reportForCompanyPostalCode",
	"reportAsCompanySiret",
	"customInfo",
	"wasteCode",
	"wastePop",
	"wasteIsDangerous",
	"receptionDate",
	"wasteDescription",
	"wasteCodeBale",
	"wasteDap",
	"weightValue",
	"weightIsEstimate",
	volume,
	"parcelInseeCodes"::text as "parcelInseeCodes",
	"parcelNumbers"::text as "parcelNumbers",
	"parcelCoordinates"::text as "parcelCoordinates",
	"initialEmitterCompanyType",
	"initialEmitterCompanyOrgId",
	"initialEmitterCompanyName",
	"initialEmitterCompanyAddress",
	"initialEmitterCompanyPostalCode",
	"initialEmitterCompanyCity",
	"initialEmitterCompanyCountryCode",
	"initialEmitterMunicipalitiesInseeCodes"::text as "initialEmitterMunicipalitiesInseeCodes",
	"emitterCompanyType",
	"emitterCompanyOrgId",
	"emitterCompanyName",
	"emitterPickupSiteAddress",
	"emitterPickupSitePostalCode",
	"emitterPickupSiteCity",
	"emitterPickupSiteCountryCode",
	"emitterCompanyAddress",
	"emitterCompanyPostalCode",
	"emitterCompanyCity",
	"emitterCompanyCountryCode",
	"brokerCompanySiret",
	"brokerCompanyName",
	"brokerRecepisseNumber",
	"traderCompanySiret",
	"traderCompanyName",
	"traderRecepisseNumber",
	"operationCode",
	"operationMode",
	"noTraceability",
	"movementNumber",
	"nextOperationCode",
	"isUpcycled",
	"destinationParcelInseeCodes"::text as "destinationParcelInseeCodes",
	"destinationParcelNumbers"::text as "destinationParcelNumbers",
	"destinationParcelCoordinates"::text as "destinationParcelCoordinates",
	"transporter1TransportMode",
	"transporter1CompanyType",
	"transporter1CompanyOrgId",
	"transporter1RecepisseIsExempted",
	"transporter1RecepisseNumber",
	"transporter1CompanyName",
	"transporter1CompanyAddress",
	"transporter1CompanyPostalCode",
	"transporter1CompanyCity",
	"transporter1CompanyCountryCode",
	"transporter2TransportMode",
	"transporter2CompanyType",
	"transporter2CompanyOrgId",
	"transporter2RecepisseIsExempted",
	"transporter2RecepisseNumber",
	"transporter2CompanyName",
	"transporter2CompanyAddress",
	"transporter2CompanyPostalCode",
	"transporter2CompanyCity",
	"transporter2CompanyCountryCode",
	"transporter3TransportMode",
	"transporter3CompanyType",
	"transporter3CompanyOrgId",
	"transporter3RecepisseIsExempted",
	"transporter3RecepisseNumber",
	"transporter3CompanyName",
	"transporter3CompanyAddress",
	"transporter3CompanyPostalCode",
	"transporter3CompanyCity",
	"transporter3CompanyCountryCode",
	"transporter4TransportMode",
	"transporter4CompanyType",
	"transporter4CompanyOrgId",
	"transporter4RecepisseIsExempted",
	"transporter4RecepisseNumber",
	"transporter4CompanyName",
	"transporter4CompanyAddress",
	"transporter4CompanyPostalCode",
	"transporter4CompanyCity",
	"transporter4CompanyCountryCode",
	"transporter5TransportMode",
	"transporter5CompanyType",
	"transporter5CompanyOrgId",
	"transporter5RecepisseIsExempted",
	"transporter5RecepisseNumber",
	"transporter5CompanyName",
	"transporter5CompanyAddress",
	"transporter5CompanyPostalCode",
	"transporter5CompanyCity",
	"transporter5CompanyCountryCode",
	"emitterPickupSiteName",
	"isDirectSupply",
	"ecoOrganismeName",
	"ecoOrganismeSiret",
	"sisIdentifier",
	"ttdImportNumber"
from
	"default$default"."RegistryIncomingTexs"

-- data_eng."RegistryIncomingWaste" source
create or replace
view data_eng."RegistryIncomingWaste"
as
select
	id,
	"createdAt",
    "updatedAt",
	"importId",
	"isLatest",
	"isCancelled",
	"createdById",
	"publicId",
	"reportForCompanySiret",
	"reportForCompanyName",
	"reportForCompanyAddress",
	"reportForCompanyCity",
	"reportForCompanyPostalCode",
	"reportAsCompanySiret",
	"wasteCode",
	"wastePop",
	"wasteIsDangerous",
	"receptionDate",
	"weighingHour",
	"wasteDescription",
	"wasteCodeBale",
	"weightValue",
	"weightIsEstimate",
	volume,
	"initialEmitterCompanyType",
	"initialEmitterCompanyOrgId",
	"initialEmitterCompanyName",
	"initialEmitterCompanyAddress",
	"initialEmitterCompanyPostalCode",
	"initialEmitterCompanyCity",
	"initialEmitterCompanyCountryCode",
	"initialEmitterMunicipalitiesInseeCodes"::text as "initialEmitterMunicipalitiesInseeCodes",
	"emitterCompanyType",
	"emitterCompanyOrgId",
	"emitterCompanyName",
	"emitterCompanyAddress",
	"emitterCompanyPostalCode",
	"emitterCompanyCity",
	"emitterCompanyCountryCode",
	"brokerCompanySiret",
	"brokerCompanyName",
	"brokerRecepisseNumber",
	"traderCompanySiret",
	"traderCompanyName",
	"traderRecepisseNumber",
	"ecoOrganismeSiret",
	"ecoOrganismeName",
	"operationCode",
	"transporter1TransportMode",
	"transporter1CompanyType",
	"transporter1CompanyOrgId",
	"transporter1RecepisseNumber",
	"transporter1CompanyName",
	"transporter1CompanyAddress",
	"transporter1CompanyPostalCode",
	"transporter1CompanyCity",
	"transporter1CompanyCountryCode",
	"transporter2TransportMode",
	"transporter2CompanyType",
	"transporter2CompanyOrgId",
	"transporter2RecepisseNumber",
	"transporter2CompanyName",
	"transporter2CompanyAddress",
	"transporter2CompanyPostalCode",
	"transporter2CompanyCity",
	"transporter2CompanyCountryCode",
	"transporter3TransportMode",
	"transporter3CompanyType",
	"transporter3CompanyOrgId",
	"transporter3RecepisseNumber",
	"transporter3CompanyName",
	"transporter3CompanyAddress",
	"transporter3CompanyPostalCode",
	"transporter3CompanyCity",
	"transporter3CompanyCountryCode",
	"transporter4TransportMode",
	"transporter4CompanyType",
	"transporter4CompanyOrgId",
	"transporter4RecepisseNumber",
	"transporter4CompanyName",
	"transporter4CompanyAddress",
	"transporter4CompanyPostalCode",
	"transporter4CompanyCity",
	"transporter4CompanyCountryCode",
	"transporter5TransportMode",
	"transporter5CompanyType",
	"transporter5CompanyOrgId",
	"transporter5RecepisseNumber",
	"transporter5CompanyName",
	"transporter5CompanyAddress",
	"transporter5CompanyPostalCode",
	"transporter5CompanyCity",
	"transporter5CompanyCountryCode",
	"movementNumber",
	"emitterPickupSiteAddress",
	"emitterPickupSiteCity",
	"emitterPickupSiteCountryCode",
	"emitterPickupSitePostalCode",
	"transporter1RecepisseIsExempted",
	"transporter2RecepisseIsExempted",
	"transporter3RecepisseIsExempted",
	"transporter4RecepisseIsExempted",
	"transporter5RecepisseIsExempted",
	"customInfo",
	"nextOperationCode",
	"noTraceability",
	"operationMode",
	"emitterPickupSiteName",
	"isDirectSupply",
	"ttdImportNumber"
from
	"default$default"."RegistryIncomingWaste";

-- data_eng."RegistryOutgoingTexs" source
create or replace
view data_eng."RegistryOutgoingTexs"
as
select
	id,
	"createdAt",
    "updatedAt",
	"importId",
	"isLatest",
	"isCancelled",
	"createdById",
	"publicId",
	"reportForCompanySiret",
	"reportForCompanyName",
	"reportForCompanyAddress",
	"reportForCompanyCity",
	"reportForCompanyPostalCode",
	"reportAsCompanySiret",
	"reportForPickupSiteName",
	"reportForPickupSiteAddress",
	"reportForPickupSitePostalCode",
	"reportForPickupSiteCity",
	"reportForPickupSiteCountryCode",
	"wasteDescription",
	"wasteCode",
	"wasteCodeBale",
	"wastePop",
	"wasteIsDangerous",
	"dispatchDate",
	"wasteDap",
	"weightValue",
	"weightIsEstimate",
	volume,
	"initialEmitterCompanyType",
	"initialEmitterCompanyOrgId",
	"initialEmitterCompanyName",
	"initialEmitterCompanyAddress",
	"initialEmitterCompanyPostalCode",
	"initialEmitterCompanyCity",
	"initialEmitterCompanyCountryCode",
	"initialEmitterMunicipalitiesInseeCodes"::text as "initialEmitterMunicipalitiesInseeCodes",
	"parcelInseeCodes"::text as "parcelInseeCodes",
	"parcelNumbers"::text as "parcelNumbers",
	"parcelCoordinates"::text as "parcelCoordinates",
	"sisIdentifier",
	"destinationCompanyType",
	"destinationCompanyOrgId",
	"destinationCompanyName",
	"destinationCompanyAddress",
	"destinationCompanyCity",
	"destinationCompanyPostalCode",
	"destinationCompanyCountryCode",
	"destinationDropSiteAddress",
	"destinationDropSitePostalCode",
	"destinationDropSiteCity",
	"destinationDropSiteCountryCode",
	"operationCode",
	"operationMode",
	"isUpcycled",
	"destinationParcelInseeCodes"::text as "destinationParcelInseeCodes",
	"destinationParcelNumbers"::text as "destinationParcelNumbers",
	"destinationParcelCoordinates"::text as "destinationParcelCoordinates",
	"movementNumber",
	"ecoOrganismeSiret",
	"ecoOrganismeName",
	"brokerCompanySiret",
	"brokerCompanyName",
	"brokerRecepisseNumber",
	"traderCompanySiret",
	"traderCompanyName",
	"traderRecepisseNumber",
	"isDirectSupply",
	"transporter1TransportMode",
	"transporter1CompanyType",
	"transporter1CompanyOrgId",
	"transporter1RecepisseIsExempted",
	"transporter1RecepisseNumber",
	"transporter1CompanyName",
	"transporter1CompanyAddress",
	"transporter1CompanyPostalCode",
	"transporter1CompanyCity",
	"transporter1CompanyCountryCode",
	"transporter2TransportMode",
	"transporter2CompanyType",
	"transporter2CompanyOrgId",
	"transporter2RecepisseIsExempted",
	"transporter2RecepisseNumber",
	"transporter2CompanyName",
	"transporter2CompanyAddress",
	"transporter2CompanyPostalCode",
	"transporter2CompanyCity",
	"transporter2CompanyCountryCode",
	"transporter3TransportMode",
	"transporter3CompanyType",
	"transporter3CompanyOrgId",
	"transporter3RecepisseIsExempted",
	"transporter3RecepisseNumber",
	"transporter3CompanyName",
	"transporter3CompanyAddress",
	"transporter3CompanyPostalCode",
	"transporter3CompanyCity",
	"transporter3CompanyCountryCode",
	"transporter4TransportMode",
	"transporter4CompanyType",
	"transporter4CompanyOrgId",
	"transporter4RecepisseIsExempted",
	"transporter4RecepisseNumber",
	"transporter4CompanyName",
	"transporter4CompanyAddress",
	"transporter4CompanyPostalCode",
	"transporter4CompanyCity",
	"transporter4CompanyCountryCode",
	"transporter5TransportMode",
	"transporter5CompanyType",
	"transporter5CompanyOrgId",
	"transporter5RecepisseIsExempted",
	"transporter5RecepisseNumber",
	"transporter5CompanyName",
	"transporter5CompanyAddress",
	"transporter5CompanyPostalCode",
	"transporter5CompanyCity",
	"transporter5CompanyCountryCode",
	"gistridNumber"
from
	"default$default"."RegistryOutgoingTexs";

-- data_eng."RegistryOutgoingWaste" source
create or replace
view data_eng."RegistryOutgoingWaste"
as
select
	id,
	"createdAt",
    "updatedAt",
	"importId",
	"isLatest",
	"isCancelled",
	"createdById",
	"publicId",
	"reportForCompanySiret",
	"reportForCompanyName",
	"reportForCompanyAddress",
	"reportForCompanyCity",
	"reportForCompanyPostalCode",
	"reportForPickupSiteName",
	"reportForPickupSiteAddress",
	"reportForPickupSitePostalCode",
	"reportForPickupSiteCity",
	"reportForPickupSiteCountryCode",
	"reportAsCompanySiret",
	"wasteDescription",
	"wasteCode",
	"wasteCodeBale",
	"wastePop",
	"wasteIsDangerous",
	"dispatchDate",
	"weightValue",
	"weightIsEstimate",
	volume,
	"initialEmitterCompanyType",
	"initialEmitterCompanyOrgId",
	"initialEmitterCompanyName",
	"initialEmitterCompanyAddress",
	"initialEmitterCompanyPostalCode",
	"initialEmitterCompanyCity",
	"initialEmitterCompanyCountryCode",
	"initialEmitterMunicipalitiesInseeCodes"::text as "initialEmitterMunicipalitiesInseeCodes",
	"destinationCompanyType",
	"destinationCompanyOrgId",
	"destinationCompanyName",
	"destinationCompanyAddress",
	"destinationCompanyCity",
	"destinationCompanyPostalCode",
	"destinationCompanyCountryCode",
	"destinationDropSiteAddress",
	"destinationDropSitePostalCode",
	"destinationDropSiteCity",
	"destinationDropSiteCountryCode",
	"movementNumber",
	"operationCode",
	"operationMode",
	"ecoOrganismeSiret",
	"ecoOrganismeName",
	"brokerCompanySiret",
	"brokerCompanyName",
	"brokerRecepisseNumber",
	"traderCompanySiret",
	"traderCompanyName",
	"traderRecepisseNumber",
	"isDirectSupply",
	"transporter1TransportMode",
	"transporter1CompanyType",
	"transporter1CompanyOrgId",
	"transporter1RecepisseIsExempted",
	"transporter1RecepisseNumber",
	"transporter1CompanyName",
	"transporter1CompanyAddress",
	"transporter1CompanyPostalCode",
	"transporter1CompanyCity",
	"transporter1CompanyCountryCode",
	"transporter2TransportMode",
	"transporter2CompanyType",
	"transporter2CompanyOrgId",
	"transporter2RecepisseIsExempted",
	"transporter2RecepisseNumber",
	"transporter2CompanyName",
	"transporter2CompanyAddress",
	"transporter2CompanyPostalCode",
	"transporter2CompanyCity",
	"transporter2CompanyCountryCode",
	"transporter3TransportMode",
	"transporter3CompanyType",
	"transporter3CompanyOrgId",
	"transporter3RecepisseIsExempted",
	"transporter3RecepisseNumber",
	"transporter3CompanyName",
	"transporter3CompanyAddress",
	"transporter3CompanyPostalCode",
	"transporter3CompanyCity",
	"transporter3CompanyCountryCode",
	"transporter4TransportMode",
	"transporter4CompanyType",
	"transporter4CompanyOrgId",
	"transporter4RecepisseIsExempted",
	"transporter4RecepisseNumber",
	"transporter4CompanyName",
	"transporter4CompanyAddress",
	"transporter4CompanyPostalCode",
	"transporter4CompanyCity",
	"transporter4CompanyCountryCode",
	"transporter5TransportMode",
	"transporter5CompanyType",
	"transporter5CompanyOrgId",
	"transporter5RecepisseIsExempted",
	"transporter5RecepisseNumber",
	"transporter5CompanyName",
	"transporter5CompanyAddress",
	"transporter5CompanyPostalCode",
	"transporter5CompanyCity",
	"transporter5CompanyCountryCode",
	"gistridNumber"
from
	"default$default"."RegistryOutgoingWaste";

-- data_eng."RegistrySsd" source
create or replace
view data_eng."RegistrySsd"
as
select
	id,
	"createdAt",
    "updatedAt",
	"importId",
	"isLatest",
	"isCancelled",
	"createdById",
	"publicId",
	"reportForCompanySiret",
	"reportForCompanyName",
	"reportForCompanyAddress",
	"reportForCompanyCity",
	"reportForCompanyPostalCode",
	"reportAsCompanySiret",
	"weightValue",
	"weightIsEstimate",
	volume,
	"wasteCode",
	"wasteCodeBale",
	"wasteDescription",
	"secondaryWasteCodes"::text as "secondaryWasteCodes",
	"secondaryWasteDescriptions"::text as "secondaryWasteDescriptions",
	"dispatchDate",
	"useDate",
	"processingDate",
	"processingEndDate",
	"operationCode",
	"operationMode",
	product,
	"administrativeActReference",
	"destinationCompanyType",
	"destinationCompanyOrgId",
	"destinationCompanyName",
	"destinationCompanyAddress",
	"destinationCompanyCity",
	"destinationCompanyPostalCode",
	"destinationCompanyCountryCode"
from
	"default$default"."RegistrySsd";



-- data_eng."RegistryTransported" source
CREATE OR REPLACE VIEW data_eng."RegistryTransported"
AS SELECT id,
    "createdAt",
    "updatedAt",
    "importId",
    "isLatest",
    "isCancelled",
    "createdById",
    "publicId",
    "reportForCompanySiret",
    "reportForCompanyName",
    "reportForCompanyAddress",
    "reportForCompanyCity",
    "reportForCompanyPostalCode",
    "reportForTransportMode",
    "reportForTransportIsWaste",
    "reportForRecepisseIsExempted",
    "reportForRecepisseNumber",
    "reportForTransportAdr",
    "reportForTransportOtherTmdCode",
    "reportForTransportPlates"::text AS "reportForTransportPlates",
    "reportAsCompanySiret",
    "wasteDescription",
    "wasteCode",
    "wasteCodeBale",
    "wastePop",
    "wasteIsDangerous",
    "collectionDate",
    "unloadingDate",
    "weightValue",
    "weightIsEstimate",
    volume,
    "emitterCompanyType",
    "emitterCompanyOrgId",
    "emitterCompanyName",
    "emitterCompanyAddress",
    "emitterCompanyPostalCode",
    "emitterCompanyCity",
    "emitterCompanyCountryCode",
    "emitterPickupSiteName",
    "emitterPickupSiteAddress",
    "emitterPickupSitePostalCode",
    "emitterPickupSiteCity",
    "emitterPickupSiteCountryCode",
    "destinationCompanyType",
    "destinationCompanyOrgId",
    "destinationCompanyName",
    "destinationCompanyAddress",
    "destinationCompanyPostalCode",
    "destinationCompanyCity",
    "destinationCompanyCountryCode",
    "destinationDropSiteAddress",
    "destinationDropSitePostalCode",
    "destinationDropSiteCity",
    "destinationDropSiteCountryCode",
    "movementNumber",
    "ecoOrganismeSiret",
    "ecoOrganismeName",
    "brokerCompanySiret",
    "brokerCompanyName",
    "brokerRecepisseNumber",
    "traderCompanySiret",
    "traderCompanyName",
    "traderRecepisseNumber",
    "gistridNumber"
   FROM "default$default"."RegistryTransported";