[project]
name = "trackdechets-elt"
version = "0.1.0"
description = "Data pipelines for Trackdechets project."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-clickhouse>=1.8.5",
    "dbt-core>=1.8.9",
    "sqlfluff-templater-dbt>=3.2.5",
    "sqlfluff>=3.2.5",
]
