STOCK_ETABLISSEMENT_DDL = """
CREATE TABLE IF NOT EXISTS stock_etablissement_tmp
(
    siren                                           String,
    nic                                             String,
    siret                                           String,
    statutDiffusionEtablissement                    LowCardinality(String),
    dateCreationEtablissement                       Nullable(Date),
    trancheEffectifsEtablissement                   LowCardinality(Nullable(String)),
    anneeEffectifsEtablissement                     Nullable(Int16),
    activitePrincipaleRegistreMetiersEtablissement  Nullable(String),
    dateDernierTraitementEtablissement              Nullable(DateTime),
    etablissementSiege                              Bool,
    nombrePeriodesEtablissement                     UInt8,
    complementAdresseEtablissement                  Nullable(String),
    numeroVoieEtablissement                         Nullable(String),
    indiceRepetitionEtablissement                   Nullable(String),
    dernierNumeroVoieEtablissement                  Nullable(String),
    indiceRepetitionDernierNumeroVoieEtablissement  Nullable(String),
    typeVoieEtablissement                           LowCardinality(Nullable(String)),
    libelleVoieEtablissement                        Nullable(String),
    codePostalEtablissement                         Nullable(String),
    libelleCommuneEtablissement                     Nullable(String),
    libelleCommuneEtrangerEtablissement             Nullable(String),
    distributionSpecialeEtablissement               LowCardinality(Nullable(String)),
    codeCommuneEtablissement                        Nullable(String),
    codeCedexEtablissement                          Nullable(String),
    libelleCedexEtablissement                       Nullable(String),
    codePaysEtrangerEtablissement                   Nullable(String),
    libellePaysEtrangerEtablissement                Nullable(String),
    identifiantAdresseEtablissement                 Nullable(String),
    coordonneeLambertAbscisseEtablissement          Nullable(String),
    coordonneeLambertOrdonneeEtablissement          Nullable(String),
    complementAdresse2Etablissement                 Nullable(String),
    numeroVoie2Etablissement                        Nullable(String),
    indiceRepetition2Etablissement                  Nullable(String),
    typeVoie2Etablissement                          LowCardinality(Nullable(String)),
    libelleVoie2Etablissement                       Nullable(String),
    codePostal2Etablissement                        Nullable(String),
    libelleCommune2Etablissement                    Nullable(String),
    libelleCommuneEtranger2Etablissement            Nullable(String),
    distributionSpeciale2Etablissement              LowCardinality(Nullable(String)),
    codeCommune2Etablissement                       Nullable(String),
    codeCedex2Etablissement                         Nullable(String),
    libelleCedex2Etablissement                      Nullable(String),
    codePaysEtranger2Etablissement                  Nullable(String),
    libellePaysEtranger2Etablissement               Nullable(String),
    dateDebut                                       Nullable(String),
    etatAdministratifEtablissement                  LowCardinality(Nullable(String)),
    enseigne1Etablissement                          Nullable(String),
    enseigne2Etablissement                          Nullable(String),
    enseigne3Etablissement                          Nullable(String),
    denominationUsuelleEtablissement                Nullable(String),
    activitePrincipaleEtablissement                 LowCardinality(Nullable(String)),
    nomenclatureActivitePrincipaleEtablissement     LowCardinality(Nullable(String)),
    caractereEmployeurEtablissement                 LowCardinality(Nullable(String))
)
ENGINE = MergeTree()
ORDER BY (siret)
"""
