select
    code_aiot,
    num_siret,
    toInt256(x),
    toInt256(y),
    adresse1,
    adresse2,
    adresse3,
    code_postal,
    code_insee,
    commune,
    raison_sociale,
    etat_activite,
    seveso,
    regime,
    priorite_nationale::bool,
    ied::bool,
    type_service_aiot,
    bovins::bool,
    porcs::bool,
    volailles::bool,
    carriere::bool,
    eolienne::bool,
    industrie::bool,
    toFloat64(nullIf(longitude, '')) as longitude,
    toFloat64(nullIf(latitude, ''))  as latitude
from
    {{ source('raw_zone_icpe', 'installations') }}
