SELECT 
    'incoming_waste' as registry_type,
    id,
    created_at,
    updated_at,
    reception_date,
    import_id,
    created_by_id,
    report_for_company_siret,
    waste_code,
    waste_pop,
    waste_is_dangerous,
    waste_description,
    waste_code_bale,
    weight_value,
    weight_is_estimate,        
    operation_code,
    operation_mode,
    initial_emitter_company_type,
    initial_emitter_company_org_id,
    initial_emitter_company_name,
    initial_emitter_company_address,
    initial_emitter_company_postal_code,
    initial_emitter_company_city,
    initial_emitter_company_country_code,
    initial_emitter_municipalities_insee_codes
FROM {{ ref('latest_registry_incoming_waste') }}

UNION ALL

SELECT 
    'incoming_texs' as registry_type,
    id,
    created_at,
    updated_at,
    reception_date,
    import_id,
    created_by_id,
    report_for_company_siret,
    waste_code,
    waste_pop,
    waste_is_dangerous,
    waste_description,
    waste_code_bale,
    weight_value,
    weight_is_estimate,        
    operation_code,
    operation_mode,
    initial_emitter_company_type,
    initial_emitter_company_org_id,
    initial_emitter_company_name,
    initial_emitter_company_address,
    initial_emitter_company_postal_code,
    initial_emitter_company_city,
    initial_emitter_company_country_code,
    initial_emitter_municipalities_insee_codes
FROM {{ ref('latest_registry_incoming_texs') }}
