SELECT 
    'outgoing_waste' as registry_type,
    id,
    created_at,
    updated_at,
    import_id,
    created_by_id,
    public_id,
    report_for_company_siret,
    report_for_company_name,
    report_for_company_address,
    report_for_company_city,
    report_for_company_postal_code,
    waste_description,
    waste_code,
    waste_code_bale,
    waste_pop,
    waste_is_dangerous,
    dispatch_date,
    weight_value,
    weight_is_estimate,
    movement_number,
    operation_code,
    operation_mode,
    is_direct_supply,
    gistrid_number,
    transporters_org_ids
FROM {{ ref('latest_registry_outgoing_waste') }}

UNION ALL

SELECT 
    'outgoing_texs' as registry_type,
    id,
    created_at,
    updated_at,
    import_id,
    created_by_id,
    public_id,
    report_for_company_siret,
    report_for_company_name,
    report_for_company_address,
    report_for_company_city,
    report_for_company_postal_code,
    waste_description,
    waste_code,
    waste_code_bale,
    waste_pop,
    waste_is_dangerous,
    dispatch_date,
    weight_value,
    weight_is_estimate,
    movement_number,
    operation_code,
    operation_mode,
    is_direct_supply,
    gistrid_number,
    transporters_org_ids
FROM {{ ref('latest_registry_outgoing_texs') }}